// ============================================================
// Mutator Rule Definitions
// Pure data file -- all 65 mutator rules plus helper functions.
// ============================================================

const RULE_CATEGORIES = {
  BOARD: 'board',
  DEATH: 'death',
  MOVEMENT: 'movement',
  RESTRICTION: 'restriction',
  SPAWN: 'spawn',
  SPECIAL: 'special',
};

const CHOICE_TYPES = {
  SQUARE: 'square',
  EMPTY_SQUARE: 'empty_square',
  PIECE: 'piece',
  FRIENDLY_PIECE: 'friendly_piece',
  ENEMY_PIECE: 'enemy_piece',
  COLUMN: 'column',
  ROW: 'row',
  TWO_SQUARES: 'two_squares',
  TWO_FRIENDLY_PAWNS: 'two_friendly_pawns',
  TWO_PIECES_SAME_COLUMN: 'two_pieces_same_column',
  FRIENDLY_BISHOP_OR_KNIGHT: 'friendly_bishop_or_knight',
  SOPHIE: 'sophie',
};

// ============================================================
// All 65 Rule Definitions
// ============================================================

const RULES = [
  // --------------------------------------------------------
  // Instant Board Manipulation (no duration)
  // --------------------------------------------------------
  {
    id: 'going_woke',
    name: 'Going Woke',
    description: 'All Pieces in the right half of the board get pushed to the left 1 square (if open)',
    flavor: 'Everybody moves left.',
    weight: 10,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'march_of_the_pawnguins',
    name: 'March of the Pawnguins',
    description: 'All Pawns advance one square if it\'s empty (no captures)',
    flavor: 'The little guys march forward.',
    weight: 10,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'the_rumbling',
    name: 'The Rumbling',
    description: 'All Pawns advance one square and kill everything they touch',
    flavor: 'The ground shakes beneath their feet.',
    weight: 5,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'they_deserved_it',
    name: 'They Deserved It',
    description: 'One random non-King Piece is killed',
    flavor: 'Justice is served... randomly.',
    weight: 8,
    duration: null,
    category: RULE_CATEGORIES.DEATH,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'born_again_christian',
    name: 'Born Again Christian',
    description: 'All Queens become Bishops',
    flavor: 'They found religion.',
    weight: 6,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'dub_thee_knight',
    name: 'Dub Thee Knight',
    description: 'Two random Pawns become Knights',
    flavor: 'Rise, noble steeds.',
    weight: 8,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'back_that_shit_up',
    name: 'Back That Shit Up',
    description: 'All Pawns move backward one square (if open)',
    flavor: 'Retreat!',
    weight: 8,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'column_swap',
    name: 'Column Swap',
    description: 'All Pieces in two random columns are swapped',
    flavor: 'Musical chairs, but vertical.',
    weight: 7,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'mind_control',
    name: 'Mind Control',
    description: 'Each player chooses one opponent non-King Piece and converts it to their team. Kings cannot be captured on the same turn',
    flavor: 'Your mind is mine now.',
    weight: 5,
    duration: 1,
    category: RULE_CATEGORIES.BOARD,
    tags: ['duration'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.ENEMY_PIECE,
    secondPlayerChoice: true,
    secondChoiceType: CHOICE_TYPES.ENEMY_PIECE,
  },
  {
    id: 'drafted_for_battle',
    name: 'Drafted for Battle',
    description: 'Both Players swap their King with a friendly Bishop or Knight of their choice',
    flavor: 'The king trades places with his champion.',
    weight: 4,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.FRIENDLY_BISHOP_OR_KNIGHT,
    secondPlayerChoice: true,
    secondChoiceType: CHOICE_TYPES.FRIENDLY_BISHOP_OR_KNIGHT,
  },
  {
    id: 'hot_drop',
    name: 'Hot Drop',
    description: 'Each Player gets a Queen in a random open square (cannot attack King this turn)',
    flavor: 'Special delivery.',
    weight: 4,
    duration: null,
    category: RULE_CATEGORIES.SPAWN,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'minefield',
    name: 'Minefield',
    description: 'Mark 2 random empty squares. If a Piece enters, they die and the mine is removed',
    flavor: 'Watch your step.',
    weight: 7,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant', 'marker', 'persistent'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'risk_it_rook',
    name: 'Risk It Rook',
    description: '50% chance for a free Rook in a random empty square. Your opponent gets 25% chance for the same',
    flavor: 'Fortune favors the bold.',
    weight: 7,
    duration: null,
    category: RULE_CATEGORIES.SPAWN,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'two_kids_in_a_trenchcoat',
    name: 'Two Kids in a Trenchcoat',
    description: 'Sacrifice 2 Pawns to put a new Bishop anywhere on the board',
    flavor: 'Totally a real Bishop, sir.',
    weight: 6,
    duration: null,
    category: RULE_CATEGORIES.SPAWN,
    tags: ['instant'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.TWO_FRIENDLY_PAWNS,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'chaaaarge',
    name: 'Chaaaarge!',
    description: 'All your Pieces move one square towards the enemy (if open)',
    flavor: 'For glory!',
    weight: 8,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'the_enemy_is_routed',
    name: 'The Enemy is Routed',
    description: 'All enemy Pieces move one square backwards (if open)',
    flavor: 'They flee in terror!',
    weight: 8,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'nuclear_fallout',
    name: 'Nuclear Fallout',
    description: '2 random empty squares cannot be entered or crossed for the rest of the game',
    flavor: 'The land is scorched.',
    weight: 5,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant', 'marker', 'permanent'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'get_up_in_their_face',
    name: 'Get Up in Their Face',
    description: 'All your Pieces slide forward until they hit an occupied square or edge',
    flavor: 'Personal space? Never heard of it.',
    weight: 6,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'a_light_breeze',
    name: 'A Light Breeze',
    description: 'All Pieces in columns D and E move one square to the right, killing anything in the way',
    flavor: 'A gentle nudge.',
    weight: 6,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'anti_camping',
    name: 'Anti-Camping',
    description: 'Pick an enemy Piece, swap it with a random friendly Piece',
    flavor: 'No hiding allowed.',
    weight: 7,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.ENEMY_PIECE,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'bottomless_pit',
    name: 'Bottomless Pit',
    description: 'Pick an empty square. For the rest of the game, any Piece who enters it dies',
    flavor: 'Don\'t look down.',
    weight: 5,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant', 'marker', 'permanent'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.EMPTY_SQUARE,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'moving_up_the_corporate_ladder',
    name: 'Moving Up the Corporate Ladder',
    description: 'Pick 2 Pieces in the same column, then swap them',
    flavor: 'Promotions for everyone!',
    weight: 7,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.TWO_PIECES_SAME_COLUMN,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'hurricane',
    name: 'Hurricane',
    description: 'Pick 1 row, all Pieces in it are pushed to the left-most empty square',
    flavor: 'Hold on to your hats.',
    weight: 6,
    duration: null,
    category: RULE_CATEGORIES.BOARD,
    tags: ['instant'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.ROW,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'sophies_choice',
    name: 'Sophie\'s Choice',
    description: 'Each player selects 2 random friendly Pieces, then picks one to kill',
    flavor: 'Choose wisely... or don\'t.',
    weight: 5,
    duration: null,
    category: RULE_CATEGORIES.DEATH,
    tags: ['instant'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.SOPHIE,
    secondPlayerChoice: true,
    secondChoiceType: CHOICE_TYPES.SOPHIE,
  },

  // --------------------------------------------------------
  // Duration Movement Modifiers
  // --------------------------------------------------------
  {
    id: 'proletariat',
    name: 'Proletariat',
    description: 'Every piece moves like a Pawn',
    flavor: 'All pieces are equal.',
    weight: 4,
    duration: [3, 7],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'movement-override'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'short_stop',
    name: 'Short Stop',
    description: 'Pieces may move a maximum of 1 square per turn',
    flavor: 'Baby steps.',
    weight: 6,
    duration: [3, 7],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'movement-limit'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'pawns_with_viagra',
    name: 'Pawns with Viagra',
    description: 'Pawns can attack left and right',
    flavor: 'They\'re feeling empowered.',
    weight: 7,
    duration: [3, 9],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'movement-add'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'trains_rights',
    name: 'Trains Rights',
    description: 'Kings move like Queens, Queens move like Kings',
    flavor: 'Role reversal.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'movement-override'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'estrogen',
    name: 'Estrogen',
    description: 'Kings can move like Queens',
    flavor: 'The King has ascended.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'movement-add'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'ice_physics',
    name: 'Ice Physics',
    description: 'Bishops, Rooks, and Queens MUST move the maximum distance',
    flavor: 'The floor is slippery.',
    weight: 6,
    duration: [3, 9],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'movement-force'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'pacman_style',
    name: 'Pacman Style',
    description: 'Pieces can wrap around the right and left sides of the board',
    flavor: 'Waka waka waka.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'movement-add'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'god_kings',
    name: 'God Kings',
    description: 'Kings are immune and can move 2 squares at a time',
    flavor: 'Bow before your ruler.',
    weight: 4,
    duration: [3, 7],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'movement-add', 'immunity'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'early_promotion',
    name: 'Early Promotion',
    description: 'Pawns promote on the 6th row instead of the 8th',
    flavor: 'Fast-tracked for success.',
    weight: 7,
    duration: [3, 9],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'promotion'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'knee_surgery',
    name: 'Knee Surgery',
    description: 'Kings can now move 2 spots in every direction',
    flavor: 'New knees, who dis?',
    weight: 6,
    duration: [3, 9],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'movement-add'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'pawns_learned_strength',
    name: 'Pawns Learned Strength',
    description: 'Pawns can push any piece forward by moving into it. Chain reactions propagate. Pieces pushed off the board are removed.',
    flavor: 'They\'ve been hitting the gym.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'movement-add'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },

  // --------------------------------------------------------
  // Duration Death Modifiers
  // --------------------------------------------------------
  {
    id: 'down_with_the_ship',
    name: 'Down with the Ship',
    description: 'Any capture also kills the capturing Piece',
    flavor: 'If I go down, you come with me.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.DEATH,
    tags: ['duration', 'death-modifier'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'second_chance',
    name: 'Second Chance',
    description: 'When any Piece dies, 50% chance it is revived in a random empty square',
    flavor: 'Not today, Death.',
    weight: 6,
    duration: [3, 9],
    category: RULE_CATEGORIES.DEATH,
    tags: ['duration', 'death-modifier'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'kamikaze',
    name: 'Kamikaze',
    description: 'When a Piece dies, 25% chance that ALL adjacent Pieces die',
    flavor: 'Taking everyone down.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.DEATH,
    tags: ['duration', 'death-modifier'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'christmas_truce',
    name: 'Christmas Truce',
    description: 'No Pieces can die',
    flavor: 'Peace on the board.',
    weight: 4,
    duration: [3, 5],
    category: RULE_CATEGORIES.DEATH,
    tags: ['duration', 'death-prevent'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'hobbit_slaughter',
    name: 'Hobbit Slaughter',
    description: 'Only Pawns can die',
    flavor: 'The little ones take the fall.',
    weight: 6,
    duration: [2, 4],
    category: RULE_CATEGORIES.DEATH,
    tags: ['duration', 'death-restrict'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'soul_link',
    name: 'Soul Link',
    description: 'If a Knight dies, both your Knights die. Same for Rooks and Bishops',
    flavor: 'Their fates are intertwined.',
    weight: 4,
    duration: [3, 9],
    category: RULE_CATEGORIES.DEATH,
    tags: ['duration', 'death-modifier'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'critical_strike',
    name: 'Critical Strike',
    description: 'Every capture has a 50% chance to also capture a random adjacent enemy Piece',
    flavor: 'Double tap.',
    weight: 6,
    duration: [3, 9],
    category: RULE_CATEGORIES.DEATH,
    tags: ['duration', 'death-modifier'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'invulnerability_potion',
    name: 'Invulnerability Potion',
    description: 'Two random Pieces on your team cannot die',
    flavor: 'Drink up.',
    weight: 5,
    duration: [3, 6],
    category: RULE_CATEGORIES.DEATH,
    tags: ['duration', 'death-prevent'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'parry',
    name: 'Parry',
    description: 'Rock Paper Scissors for a chance to stop any attack',
    flavor: 'En garde!',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.SPECIAL,
    tags: ['duration', 'rps'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },

  // --------------------------------------------------------
  // Duration Restrictions
  // --------------------------------------------------------
  {
    id: 'severe_constipation',
    name: 'Severe Constipation',
    description: 'Bishops and Knights cannot move',
    flavor: 'They\'re stuck.',
    weight: 6,
    duration: [3, 9],
    category: RULE_CATEGORIES.RESTRICTION,
    tags: ['duration', 'restriction'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'hobbit_battle',
    name: 'Hobbit Battle',
    description: 'ONLY Pawns can be moved',
    flavor: 'It\'s their time to shine.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.RESTRICTION,
    tags: ['duration', 'restriction'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'bloodthirsty',
    name: 'Bloodthirsty',
    description: 'You must make a move that captures an enemy (if possible)',
    flavor: 'Blood for the blood god.',
    weight: 6,
    duration: [3, 9],
    category: RULE_CATEGORIES.RESTRICTION,
    tags: ['duration', 'restriction'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'ice_age',
    name: 'Ice Age',
    description: 'Pieces in columns 1 and 8 are frozen',
    flavor: 'The edges freeze over.',
    weight: 6,
    duration: [3, 9],
    category: RULE_CATEGORIES.RESTRICTION,
    tags: ['duration', 'restriction', 'freeze'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'no_cowards',
    name: 'No Cowards',
    description: 'All moves must move closer to your opponent\'s side of the board',
    flavor: 'Forward, always forward.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.RESTRICTION,
    tags: ['duration', 'restriction'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'all_on_red',
    name: 'All on Red',
    description: 'Flip a coin at start of your turn, if it\'s tails you can only move your King',
    flavor: 'Feeling lucky?',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.RESTRICTION,
    tags: ['duration', 'restriction', 'chance'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },

  // --------------------------------------------------------
  // Duration Ongoing / Turn Effects
  // --------------------------------------------------------
  {
    id: 'blood_sacrifice',
    name: 'Blood Sacrifice',
    description: 'A random non-King piece dies for each player after every turn',
    flavor: 'The gods demand tribute.',
    weight: 4,
    duration: [3, 5],
    category: RULE_CATEGORIES.DEATH,
    tags: ['duration', 'ongoing', 'sacrifice'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'portal_storm',
    name: 'Portal Storm',
    description: 'Two random non-King Pieces swap places at the end of every turn',
    flavor: 'Reality is unstable.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.BOARD,
    tags: ['duration', 'ongoing'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'religious_conversion',
    name: 'Religious Conversion',
    description: 'If a Bishop moves next to an enemy Pawn, you convert it to your team',
    flavor: 'Have you heard the good word?',
    weight: 6,
    duration: [3, 9],
    category: RULE_CATEGORIES.BOARD,
    tags: ['duration', 'ongoing', 'conversion'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },

  // --------------------------------------------------------
  // Duration Player-Choice Setup
  // --------------------------------------------------------
  {
    id: 'living_bomb',
    name: 'Living Bomb',
    description: 'Pick a friendly Piece. If it\'s alive when this expires, it explodes and kills all adjacent pieces',
    flavor: 'Tick... tick... tick...',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.SPECIAL,
    tags: ['duration', 'expiry', 'explosion'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.FRIENDLY_PIECE,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'mitosis',
    name: 'Mitosis',
    description: 'Pick a Piece. It cannot move, but if alive when this expires, spawn a duplicate into an empty adjacent square',
    flavor: 'Cell division in progress.',
    weight: 6,
    duration: [3, 9],
    category: RULE_CATEGORIES.SPECIAL,
    tags: ['duration', 'expiry', 'spawn'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.PIECE,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'treasure_chest',
    name: 'Treasure Chest',
    description: 'Select a random empty square. The first Piece to enter that square is promoted',
    flavor: 'X marks the spot.',
    weight: 7,
    duration: [3, 9],
    category: RULE_CATEGORIES.SPECIAL,
    tags: ['duration', 'marker'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'mr_freeze',
    name: 'Mr. Freeze',
    description: 'Pick 1 column. All Pieces in it are frozen and immune until this expires',
    flavor: 'Ice to meet you.',
    weight: 6,
    duration: [3, 9],
    category: RULE_CATEGORIES.RESTRICTION,
    tags: ['duration', 'freeze', 'immunity'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.COLUMN,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'portal_3',
    name: 'Portal 3',
    description: 'Pick 2 squares. At the end of every turn, those two squares swap',
    flavor: 'Now you\'re thinking with portals.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.SPECIAL,
    tags: ['duration', 'ongoing', 'swap'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.TWO_SQUARES,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'no_mans_land',
    name: 'No Man\'s Land',
    description: 'Pick 1 column. No Pieces may enter or cross the column. Pieces in it can leave.',
    flavor: 'Danger zone.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.RESTRICTION,
    tags: ['duration', 'block'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.COLUMN,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'cash_grab',
    name: 'Cash Grab',
    description: 'Any Piece that reaches the back line can promote',
    flavor: 'Money money money.',
    weight: 7,
    duration: [3, 9],
    category: RULE_CATEGORIES.MOVEMENT,
    tags: ['duration', 'promotion'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'tornado',
    name: 'Tornado',
    description: 'Pick an empty square. If any Piece *can* move to that square, it must',
    flavor: 'You\'re getting sucked in.',
    weight: 4,
    duration: [3, 9],
    category: RULE_CATEGORIES.RESTRICTION,
    tags: ['duration', 'restriction'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.EMPTY_SQUARE,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },

  // --------------------------------------------------------
  // Duration Expiry Triggers
  // --------------------------------------------------------
  {
    id: 'summoning_ritual',
    name: 'Summoning Ritual',
    description: 'When this expires, whichever Player has more Pieces on the 4 corner spots gets a Rook at a random empty square',
    flavor: 'The ritual is complete.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.SPECIAL,
    tags: ['duration', 'expiry', 'spawn'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'call_down_lightning',
    name: 'Call Down Lightning',
    description: 'Mark a random empty square. When this expires, whoever controls that square kills a random enemy piece',
    flavor: 'Thor is watching.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.SPECIAL,
    tags: ['duration', 'expiry', 'kill'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'get_the_fuck_off',
    name: 'Get the Fuck Off',
    description: 'Pick 2 squares on the board. When this expires, any Pieces on those squares die',
    flavor: 'You were warned.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.SPECIAL,
    tags: ['duration', 'expiry', 'kill'],
    requiresChoice: true,
    choiceType: CHOICE_TYPES.TWO_SQUARES,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'gigachad_aura',
    name: 'Gigachad Aura',
    description: 'When this expires, all Pieces adjacent to a King die',
    flavor: 'The aura is overwhelming.',
    weight: 4,
    duration: [3, 9],
    category: RULE_CATEGORIES.SPECIAL,
    tags: ['duration', 'expiry', 'kill'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
  {
    id: 'time_bomb',
    name: 'Time Bomb',
    description: 'All Pieces in Column E die when this rule expires',
    flavor: 'Tick tock.',
    weight: 5,
    duration: [3, 9],
    category: RULE_CATEGORIES.SPECIAL,
    tags: ['duration', 'expiry', 'kill'],
    requiresChoice: false,
    choiceType: null,
    secondPlayerChoice: false,
    secondChoiceType: null,
  },
];

// ============================================================
// Helper Functions
// ============================================================

function getRuleById(id) {
  return RULES.find(r => r.id === id) || null;
}

function getEligibleRules(activeRuleIds, disabledRuleIds = []) {
  const disabledSet = disabledRuleIds instanceof Set ? disabledRuleIds : new Set(disabledRuleIds);
  return RULES.filter(r => !activeRuleIds.includes(r.id) && !disabledSet.has(r.id));
}

function selectWeightedRandom(rules, count) {
  const selected = [];
  const pool = [...rules];
  for (let i = 0; i < count && pool.length > 0; i++) {
    const totalWeight = pool.reduce((sum, r) => sum + r.weight, 0);
    let roll = Math.random() * totalWeight;
    let chosen = null;
    for (let j = 0; j < pool.length; j++) {
      roll -= pool[j].weight;
      if (roll <= 0) { chosen = j; break; }
    }
    if (chosen === null) chosen = pool.length - 1;
    selected.push(pool.splice(chosen, 1)[0]);
  }
  return selected;
}

// ============================================================
// Exports
// ============================================================

module.exports = {
  RULE_CATEGORIES,
  CHOICE_TYPES,
  RULES,
  getRuleById,
  getEligibleRules,
  selectWeightedRandom,
};
